cc_library(
    name = "lz4",
    srcs = [
        "lz4.h",
        "lz4frame.h",
        "lz4frame_static.h",
        "lz4hc.h",
        "xxhash.h",
        "lz4.c",
        "lz4frame.c",
        "lz4hc.c",
        "xxhash.c"
    ],
    hdrs = [
        "lz4.h",
        "lz4frame.h",
        "lz4frame_static.h",
        "lz4hc.h",
        "xxhash.h",
        "lz4.c",
    ],
    includes = [
        "lz4.h",
        "lz4hc.h",
        "lz4frame.h",
    ],
    visibility = ["//visibility:public"],
)